### ISSUE TITLE
Make Chat-GPT  response can be dismissed

### ISSUE THREAD

**Issue by SinoAHpx** [josStorer/chatGPT-search-engine-extension#10]

**Comment by josStorer** [comment]
[released](https://github.com/josStorer/chatGPT-search-engine-extension/releases) just now, actually I can't really dismiss a response with current APIs, so I added a collapse icon

**Comment by SinoAHpx** [comment]
That's already cool, and I wonder if there could be a option that collapse the response by default

**Comment by josStorer** [comment]
From my point of view, this seems meaningless, if default collapsed is turned on, users will never see any response, but when users enter some questions, they are always expecting some replies, if you want to avoid some searches getting replies, you should click on the extension icon, then turn on manual mode

**Comment by SinoAHpx** [comment]
Another question is... 好像俺俩都是中国人（
然后回到这个 issue 的正题上来，因为谷歌搜索在大多数时候都会提供一个相对来说还不错的答案，所以这时候 Chat-GPT 的响应并不是每次都是被需要的，甚至在某种程度上还会降低获取信息的效率。所以我认为提供一个默认隐藏的选项，就可以只在需要的时候查看 Chat-GPT 的响应。

**Comment by josStorer** [comment]
有这个功能, 安装扩展后, 点击扩展图标, 你会看到这个
![image](https://user-images.githubusercontent.com/13366013/210080252-f3ae9359-1fa2-40ae-a8e2-4a25a8ecdb3b.png)
你可以选择, 当的输入的问题结尾包含"问号"时触发chatGPT, 或者手动点击触发

**Comment by josStorer** [comment]
当然手动点击跟你描述的还是有差异, 因为点击后需要等待回答生成
而如果按照你设想的, 默认隐藏
意味着, 你搜索时已经开始生成回答, 你展开后能直接看到完成的回答

不过我想, 既然用户已经考虑默认不要看到回答了, 还是使用这个手动触发模式, 帮openAI省点计算资源吧, 总是请求有些浪费

**Comment by SinoAHpx** [comment]
👍
