### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by josStorer** [josStorer/chatGPT-search-engine-extension#11]
Unexpected non-whitespace character after JSON at position 4
Always hav this issue

_Originally posted by @sohaiBiu99 in https://github.com/josStorer/chatGPT-search-engine-extension/issues/6#issuecomment-1376630261_

**Comment by josStorer** [comment]
what's your extension version

**Comment by sohaiBiu99** [comment]
v1.12.3, but I tried older ver until v1.6.2, all have the same issue, my friends also like that

**Comment by josStorer** [comment]
@sohaiBiu99 what browser are you using, and could you provide some screenshots? I have to reproduce the issue

**Comment by sohaiBiu99** [comment]
Google Chrome
![image](https://user-images.githubusercontent.com/69910797/211462777-23d6f251-3f81-4258-9aed-54008959a129.png)

**Comment by josStorer** [comment]
@sohaiBiu99 

The good news is that I can reproduce this issue, the bad news is that this issue also exists on the official website, it occurs when the generated answer is too long, and the openai api stops sending the response, so what I did is just showing the error message in the extension card

You can see `Fix answer being overwritten due to " network error"` in the readme page, which refers to this issue

**Comment by sohaiBiu99** [comment]
This is not due to network error. but previous version like v1.6.2 don't have this issue right? So you mean it cannot generate long answer now? 
![image](https://user-images.githubusercontent.com/69910797/211467669-139be9a2-9870-4592-88a2-692070ac66c4.png)

This is the screenshot before in v1.6.2, it can produce long respond, but now even I use back the v1.6.2, it still hav the issue
![image](https://user-images.githubusercontent.com/69910797/211467975-336112dd-d5cd-41b8-8f68-e79f15e48d42.png)

**Comment by josStorer** [comment]
@sohaiBiu99 
I have tested further, and although errors can occur on the official website, the probability is much lower, and I think there may be some api changes recently that I need some time to process

**Comment by josStorer** [comment]
I mean that sometimes on the official website, you will get `network error` when the answer is too long

**Comment by josStorer** [comment]
I'm sure this is due to an openai api change recently, so any version of this extension has this problem, and I need to do some updates, I will let you know once I've solved it

**Comment by josStorer** [comment]
same issue: https://github.com/transitive-bullshit/chatgpt-api/issues/247

**Comment by sohaiBiu99** [comment]
Thank you!

**Comment by josStorer** [comment]
@sohaiBiu99 
released https://github.com/josStorer/chatGPT-search-engine-extension/releases/tag/v1.20.0
