### ISSUE TITLE
搜索显示“OpenAI Security Check Required Please open https://chat.openai.com”

### ISSUE THREAD

**Issue by edhnt455** [josStorer/chatGPT-search-engine-extension#13]
![image](https://user-images.githubusercontent.com/59108157/215479189-622406eb-e089-4a31-b98a-fa647147c021.png)
是访问数量到上限了嘛。能不能用我自己申请key，如果可以的话请说一下在哪设置，谢谢

**Comment by josStorer** [comment]
你打开官网后再刷新能正常使用吗, 目前这个提示只是因为官网添加了Cloudflare验证引起的, 必须每过一段时间打开一次官网, 自己的key目前只能用gpt-3, 效果一般, 等官网放了chatGPT的api和授权方案我会更新

**Comment by edhnt455** [comment]
好的我再试试

**Comment by josStorer** [comment]
刚刚更新了一个版本, 现在你可以用自己的key, 自己选择模型, 但是gpt-3在对话上面的效果确实比chatGPT差不少
![image](https://user-images.githubusercontent.com/13366013/216607363-4b357cad-4fa0-4877-b978-e651ec90284c.png)

**Comment by edhnt455** [comment]
好的谢谢大佬
