### ISSUE TITLE
Cannot use in Safari: UNAUTHORIZED

### ISSUE THREAD

**Issue by billzt** [josStorer/chatGPT-search-engine-extension#18]
It shows:

![image](https://user-images.githubusercontent.com/1146090/219232662-2eb385e7-b312-4e55-89a8-ddb0b917481d.jpeg)

And in the console:

![image](https://user-images.githubusercontent.com/1146090/219232866-53a499fd-a003-47fd-afdf-264f462a1deb.jpeg)

I've tried to log in and refresh, but no use

**Comment by josStorer** [comment]
did you open the highlight link?
it works on my mac

<img width="1820" alt="image" src="https://user-images.githubusercontent.com/13366013/219277278-159ac4eb-c8ab-4d70-a377-43f2d5032ba8.png">

**Comment by josStorer** [comment]
the second link `http://chat.openai.com/api/auth/session`

**Comment by billzt** [comment]
@josStorer Yes, I opened it. No problems.

Does you browser shows `Unrecognized Content-Security-Policy directive 'require-trusted-types-for'. Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.` in the console?

**Comment by josStorer** [comment]
only `Unrecognized Content-Security-Policy directive 'require-trusted-types-for'`, and seems that not related to this extension, even I disable all my extensions, it still displays

**Comment by billzt** [comment]
OK.I edited the title.

However, no matter how many times I opened `https://chat.openai.com/api/auth/session`, it still shows `UNAUTHORIZED `

Any method to debug it? e.g. using console window

**Comment by josStorer** [comment]
I'm afraid you have to debug by building from the source code. At https://github.com/josStorer/chatGPT-search-engine-extension/blob/main/src/background/index.mjs#L20, you can use console.debug to display your config info, and view it through Safari - Develop - Web Extension Background Pages. At https://github.com/josStorer/chatGPT-search-engine-extension/blob/main/src/content-script/index.jsx#L50, you can check whether the accessToken has been correctly obtained.

**Comment by josStorer** [comment]
the build steps are:
npm install
npm run build
npm run build:safari

**Comment by josStorer** [comment]
try this [safari.dmg.zip](https://github.com/josStorer/chatGPT-search-engine-extension/files/10752738/safari.dmg.zip), i added extra debug info

**Comment by billzt** [comment]
@josStorer Thank you. I have installed it (and disabled all other extensions)

But there is no debug info output.

![image](https://user-images.githubusercontent.com/1146090/219285017-21184662-6853-4df0-98ec-898187117dd4.jpeg)
![image](https://user-images.githubusercontent.com/1146090/219285095-96a9c736-8ecc-42a1-8ae4-2090f06b0904.jpeg)

**Comment by josStorer** [comment]
check the console window of the background page and `https://chat.openai.com/api/auth/session`

<img width="723" alt="image" src="https://user-images.githubusercontent.com/13366013/219284684-e91d8596-58d7-49a9-ad27-5e7eead5e165.png">
<img width="1713" alt="image" src="https://user-images.githubusercontent.com/13366013/219284993-0295fe9c-8cfb-4d1d-9066-815bb607a94c.png">

**Comment by billzt** [comment]
I understand.

I missed `Always Allow on Every Website`. I only allowed for google.com

**Comment by AndrielF** [comment]
> I understand.
> 
> I missed `Always Allow on Every Website`. I only allowed for google.com

I did the same haha. Thanks, also allow on chat.openai.com and it worked
