### ISSUE TITLE
Not working with dark mode in safari/mac

### ISSUE THREAD

**Issue by Algebra0787** [josStorer/chatGPT-search-engine-extension#20]
Text in the widget is the same colour as the widget background when dark mode is enabled on a mac, meaning that you cannot see the text. 

<img width="488" alt="Screenshot 03-03-2023 at 08_49_51PM" src="https://user-images.githubusercontent.com/125733189/222826771-db546b14-d0fd-4cad-9ddb-d7a4ecd3722f.png">

**Comment by josStorer** [comment]
updated, check [v1.26.0](https://github.com/josStorer/chatGPT-search-engine-extension/releases)
