### ISSUE TITLE
Add syntax highlighting to a code block.

### ISSUE THREAD

**Issue by TeachMeJavaTonight** [josStorer/chatGPT-search-engine-extension#22]
If possible, I would appreciate code block segmentation or syntax highlighting.
![image](https://user-images.githubusercontent.com/104610452/222880954-a0c35888-3950-4ecc-9944-2bfd76550a35.png)

**Comment by josStorer** [comment]
This feature has actually been implemented, but sometimes ChatGPT doesn't wrap the generated code in `````` symbols, so occasionally it doesn't work.

**Comment by josStorer** [comment]
Can you please make a few more attempts?

**Comment by acasto** [comment]
It seems to be working here. <img width="337" alt="image" src="https://user-images.githubusercontent.com/199140/222881189-3de4d534-4c84-46a6-9bbd-c831d85aaf7f.png">
