### ISSUE TITLE
Is this option using the gpt-3.5-turbo model?

### ISSUE THREAD

**Issue by devyujie** [josStorer/chatGPT-search-engine-extension#25]
![image](https://user-images.githubusercontent.com/48620527/223307568-01e7c7ea-0f63-4df0-a21e-086fc114633d.png)

**Comment by josStorer** [comment]
yes

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: yujie ***@***.***>
Sent: Tuesday, March 7, 2023 10:51:19 AM
To: josStorer/chatGPT-search-engine-extension ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [josStorer/chatGPT-search-engine-extension] Is this option using the gpt-3.5-turbo model? (Issue #25)


[image]<https://user-images.githubusercontent.com/48620527/223307568-01e7c7ea-0f63-4df0-a21e-086fc114633d.png>

―
