### ISSUE TITLE
希望可以优化一下对话的显示效果

### ISSUE THREAD

**Issue by VsentKB** [josStorer/chatGPT-search-engine-extension#26]
<img width="647" alt="ss" src="https://user-images.githubusercontent.com/49086968/223317353-7cbfafe3-8415-4176-94d9-cb8c27e36de7.png">
希望可以在这下面同样增加下划线便于观看。
当然，如果可以实现bing ai那种对话气泡的样式，那就再好不过了

**Comment by josStorer** [comment]
收到, 下个版本会改进, 气泡样式目前暂不打算添加, 主要是会造成长对话和特殊格式显示时的大量控件浪费, 并且不利于为每个对话块添加操作按钮

**Comment by josStorer** [comment]
已更新, 目前移动到新仓库: https://github.com/josStorer/chatGPTBox
更新日志: https://github.com/josStorer/chatGPT-search-engine-extension/releases/tag/v2.0.0
