### ISSUE TITLE
You do not have access to chat.openai.com.

### ISSUE THREAD

**Issue by AyushRajgor** [josStorer/chatGPT-search-engine-extension#30]
so I follow your code to see how you make request to chat.openai.com for conversation. I tried to do same in postman but give me error with Access Denied You do not have access to chat.openai.com.

 

![Screenshot (3)](https://user-images.githubusercontent.com/76404080/229495711-d22796cf-7c81-49c5-8ea8-3d5db1e8edb1.png)
![Screenshot (4)](https://user-images.githubusercontent.com/76404080/229495719-e2c019dc-2d42-4d38-b128-df4c3ab3a845.png)

**Comment by josStorer** [comment]
https://github.com/josStorer/chatGPTBox/issues/142
