### ISSUE TITLE
大概是这个内容：）

### ISSUE THREAD

**Issue by 19165760135** [josStorer/chatGPT-search-engine-extension#8]
无法加载扩展

文件
D:\Program Files (x86)\chatGPT-search-engine-extension-1.6.2

错误清单文件丢失或不可读取

重试

取消

**Comment by josStorer** [comment]
你这是把zip解压了吧, 不需要解压, 直接选择读取zip

**Comment by josStorer** [comment]
@19165760135 抱歉打扰了, 我先前发现直接读取zip, 浏览器会解压到一个临时目录, 可能一段时间后被清理导致插件失效

如果你还在使用的话, 不知道你所提的问题是否依然存在, 如果有问题可以继续说明
